//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeatureType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FeatureType()
        {
            this.FeatureTypeDetails = new HashSet<FeatureTypeDetail>();
        }
    
        public int Id { get; set; }
        public int CategoryId { get; set; }
        public int BaseFeatureTypeId { get; set; }
        public int Priority { get; set; }
    
        public virtual BaseFeatureType BaseFeatureType { get; set; }
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FeatureTypeDetail> FeatureTypeDetails { get; set; }
    }
}
