//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocalLink
    {
        public int Id { get; set; }
        public Nullable<int> LanguageId { get; set; }
        public string Caption { get; set; }
        public string Content { get; set; }
        public Nullable<int> Priority { get; set; }
    }
}
