//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.PackageOrderDetails = new HashSet<PackageOrderDetail>();
        }
    
        public int Id { get; set; }
        public int InvoiceId { get; set; }
        public System.Guid ProductFeatureId { get; set; }
        public System.DateTime Date { get; set; }
        public int State { get; set; }
        public decimal Price { get; set; }
        public int Quantity { get; set; }
        public Nullable<int> RecipientTypeId { get; set; }
        public Nullable<int> OccasionId { get; set; }
    
        public virtual Invoice Invoice { get; set; }
        public virtual ProductFeature ProductFeature { get; set; }
        public virtual RecipientType RecipientType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PackageOrderDetail> PackageOrderDetails { get; set; }
    }
}
