//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewFeatureTypeDetail
    {
        public int Id { get; set; }
        public int FeatureTypeId { get; set; }
        public int Priority { get; set; }
        public string Name { get; set; }
        public int BaseFeatureTypeDetailId { get; set; }
    }
}
