//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewOrder
    {
        public int Id { get; set; }
        public System.Guid ProductFeatureId { get; set; }
        public System.DateTime Date { get; set; }
        public int State { get; set; }
        public decimal Price { get; set; }
        public int Quantity { get; set; }
        public Nullable<int> RecipientTypeId { get; set; }
        public Nullable<int> OccasionId { get; set; }
        public string Name { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public int TotalQuantity { get; set; }
        public string IconUrl { get; set; }
        public int CategoryId { get; set; }
        public string UserId { get; set; }
        public Nullable<System.Guid> TempCartId { get; set; }
        public int InvoiceId { get; set; }
        public string Title { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public string TransactionNo { get; set; }
        public decimal Subtotal { get; set; }
        public decimal Tax { get; set; }
        public decimal Total { get; set; }
        public decimal AmountDue { get; set; }
        public bool Finished { get; set; }
        public Nullable<int> InvoiceState { get; set; }
    }
}
