//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewProductCategoryField
    {
        public int Id { get; set; }
        public int ProductId { get; set; }
        public int CategoryFieldId { get; set; }
        public int CategoryId { get; set; }
        public string CategoryFieldName { get; set; }
        public Nullable<int> Priority { get; set; }
        public string CategoryName { get; set; }
        public string ProductName { get; set; }
    }
}
