//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewProductFeatureFullInfo
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> ParentId { get; set; }
        public int ProductId { get; set; }
        public Nullable<int> FeatureTypeDetailId { get; set; }
        public string FeatureTypeDetailName { get; set; }
        public string FeatureTypeName { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> FeatureTypeId { get; set; }
        public int Priority { get; set; }
        public Nullable<int> FeatureTypePriority { get; set; }
        public Nullable<int> FeatureTypeDetailPriority { get; set; }
        public string IconUrl { get; set; }
        public Nullable<bool> Showcase { get; set; }
        public string Description { get; set; }
        public int CategoryId { get; set; }
        public string ImageTitle { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<int> ImagePriority { get; set; }
        public string LinkUrl { get; set; }
        public string CategoryName { get; set; }
        public string ProductDescription { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> BaseFeatureTypeDetailId { get; set; }
    }
}
