//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewPersonInRole
    {
        public string Name { get; set; }
        public string Identifier { get; set; }
        public bool Sex { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string AcademicInfoNames { get; set; }
        public string UserId { get; set; }
        public int Id { get; set; }
        public string AcademicInfoValues { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> RegisterDate { get; set; }
        public string RoleName { get; set; }
        public string RoleId { get; set; }
        public string UserDefiner { get; set; }
        public Nullable<System.DateTime> LastSignIn { get; set; }
        public string StreetLine1 { get; set; }
        public string StreetLine2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string ProfilePictureUrl { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<int> PhoneCode { get; set; }
        public Nullable<short> NumCode { get; set; }
        public string Iso { get; set; }
        public string Iso3 { get; set; }
        public Nullable<int> CountryId { get; set; }
        public string Country { get; set; }
        public bool AllowAcceptReject { get; set; }
    }
}
